// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apl_movimentos_manuais.Infra.Persistence.Context;

namespace apl_movimentos_manuais.Infra.Persistence.Migrations
{
    [DbContext(typeof(MovimentosManuaisContext))]
    [Migration("20191127004049_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apl_movimentos_manuais.Domain.Entities.MovimentoManual", b =>
                {
                    b.Property<decimal>("DataMes")
                        .HasColumnName("DAT_MES")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<decimal>("DataAno")
                        .HasColumnName("DAT_ANO")
                        .HasColumnType("numeric(4, 0)");

                    b.Property<decimal>("NumLancamento")
                        .HasColumnName("NUM_LANCAMENTO")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("CodProduto")
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("CodCosif")
                        .HasColumnName("COD_COSIF")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasColumnName("COD_USUARIO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<DateTime>("DataMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DAT_MOVIMENTO")
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DesDescricao")
                        .IsRequired()
                        .HasColumnName("DES_DESCRICAO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("Valor")
                        .HasColumnName("VAL_VALOR")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("DataMes", "DataAno", "NumLancamento", "CodProduto", "CodCosif");

                    b.HasIndex("CodProduto", "CodCosif");

                    b.ToTable("MOVIMENTO_MANUAL");
                });

            modelBuilder.Entity("apl_movimentos_manuais.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("DesProduto")
                        .HasColumnName("DES_PRODUTO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("StaStatus")
                        .HasColumnName("STA_STATUS")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CodProduto");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("apl_movimentos_manuais.Domain.Entities.ProdutoCosif", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasColumnName("COD_PRODUTO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("CodCosif")
                        .HasColumnName("COD_COSIF")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("CodClassificacao")
                        .HasColumnName("COD_CLASSIFICACAO")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("StaStatus")
                        .HasColumnName("STA_STATUS")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("CodProduto", "CodCosif");

                    b.ToTable("PRODUTO_COSIF");
                });

            modelBuilder.Entity("apl_movimentos_manuais.Domain.Entities.MovimentoManual", b =>
                {
                    b.HasOne("apl_movimentos_manuais.Domain.Entities.ProdutoCosif", "Cod")
                        .WithMany("MovimentoManual")
                        .HasForeignKey("CodProduto", "CodCosif")
                        .HasConstraintName("FK_MOVIMENTO_MANUAL_PRODUTO_COSIF");
                });

            modelBuilder.Entity("apl_movimentos_manuais.Domain.Entities.ProdutoCosif", b =>
                {
                    b.HasOne("apl_movimentos_manuais.Domain.Entities.Produto", "CodProdutoNavigation")
                        .WithMany("ProdutoCosif")
                        .HasForeignKey("CodProduto")
                        .HasConstraintName("FK_PRODUTO_COSIF_PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
